---
title: "BHRC SOBP Figures"
output: html_notebook
---

```{r}
library(ggplot2)
#library(tidyr)
library(tidyverse)

```

```{r}
bhrc <- read_csv("~/Documents/neptune/data/processed/bhrc_sobp_data.csv", show_col_types = FALSE)

```

```{r}

p <- ggplot(bhrc, aes(x = bag_z_scored, color = adhd, fill = adhd)) + 
  geom_density(alpha = 0.6) + 
  theme_minimal() +
  scale_x_continuous(limits=c(-4,4)) + 
  labs(x = "zBAG", y = "", color = "ADHD", fill = "ADHD") +
  scale_color_manual(values = c("#FF69B4", "#4682B4")) +
  scale_fill_manual(values = c("#FF69B4", "#4682B4")) + 
  theme(legend.position = c(0.11, 0.85),
        legend.text = element_text(size=12),
        legend.title = element_blank(), , text=element_text(size=15))

median_adhd <- median(bhrc[bhrc$adhd == "Yes", ]$bag_z_scored)
median_no_adhd <- median(bhrc[bhrc$adhd == "No", ]$bag_z_scored)

p <- p + geom_vline(xintercept = median_adhd, color = "#4682B4", linetype = "dashed")
p <- p + geom_vline(xintercept = median_no_adhd, color = "#FF69B4", linetype = "dashed")
p <- p + ggtitle("ADHD")

p <- p + annotate("text", x = 0.3, y = 0.43, label = paste0(round((median_adhd - median_no_adhd) * 12, 2), " months"), hjust = 0, size = 5)

# p <- p + annotate("text", x = 2.5, y = 0.37, label = "β = -0.27, SE = 0.21599, \nCI[-0.689, 0.159], p = 0.22", size = 10, color = "blue")

print(p)
ggsave("adhd_bhrc_sobp_distribution.png", plot = p, width = 20, height = 15, units = "cm", dpi = 800)
```





```{r}

p <- ggplot(bhrc, aes(x = bag_z_scored, color = anxiety, fill = anxiety)) + 
  geom_density(alpha = 0.6) + 
  theme_minimal() + 
  scale_x_continuous(limits=c(-4,4)) + 
  labs(x = "zBAG", y = "", color = "Anxiety", fill = "Anxiety") +
  scale_color_manual(values = c("#FF69B4", "#4682B4")) +
  scale_fill_manual(values = c("#FF69B4", "#4682B4")) + 
  theme(legend.position = c(0.11, 0.85),
        legend.text = element_text(size=12),
        legend.title = element_blank(), , text=element_text(size=15))

median_anx <- median(bhrc[bhrc$anxiety == "Yes", ]$bag_z_scored)
median_no_anx <- median(bhrc[bhrc$anxiety == "No", ]$bag_z_scored)

p <- p + geom_vline(xintercept = median_anx, color = "#4682B4", linetype = "dashed")
p <- p + geom_vline(xintercept = median_no_anx, color = "#FF69B4", linetype = "dashed")
p <- p + ggtitle("Anxiety")

p <- p + annotate("text", x = 0.3, y = 0.43, label = paste0(round((median_anx - median_no_anx) * 12, 2), " months"), hjust = 0, size = 5)

# p <- p + annotate("text", x = 2.5, y = 0.37, label = "β = -0.15, SE = -0.15, \nCI[-0.54, 0.23], p = 0.44", size = 10, color = "blue")

print(p)
ggsave("../figures/anxiety_bag_sobp_distribution.png", plot = p, width = 20, height = 15, units = "cm", dpi = 800)

```
```{r}

bhrc$group[bhrc$group == 'FHR (SMI)'] <- 'FHR'

p <- ggplot(bhrc, aes(x = bag_z_scored, color = group, fill = group)) + 
  geom_density(alpha = 0.6) + 
  theme_minimal() +
  labs(x = "zBAG", y = "Proportion", color = "Familial Risk Group", fill = "Familial Risk Group") +
  scale_x_continuous(limits=c(-4,4)) + 
  scale_color_manual(values = c("#FF69B4", "#4682B4")) +
  scale_fill_manual(values = c("#FF69B4", "#4682B4")) + 
  theme(legend.position = c(0.11, 0.85),
        legend.text = element_text(size=12),
        legend.title = element_blank(), text=element_text(size=15))

median_fhr <- median(bhrc[bhrc$group == "FHR", ]$bag_z_scored)
median_ctrls <- median(bhrc[bhrc$group == "Ctrls", ]$bag_z_scored)

p <- p + geom_vline(xintercept = median_fhr, color = "#4682B4", linetype = "dashed")
p <- p + geom_vline(xintercept = median_ctrls, color = "#FF69B4", linetype = "dashed")
p <- p + ggtitle("Familial Risk Group")

p <- p + annotate("text", x = -1.8, y = 0.43, label = paste0(round((median_fhr - median_ctrls) * 12, 2), " months"), hjust = 0, size = 5)

#p <- p + annotate("text", x = 2.5, y = 0.37, label = "β = -0.01, SE = -0.01, \nCI [-0.45, 0.424], p = 0.96", size = 10, color = "blue")

print(p)

ggsave("../figures/fhr_bag_sobp_distribution.png", plot = p, width = 20, height = 15, units = "cm", dpi = 800)

```

```{r}
head(bhrc)
```









